{% set version = "1.8.0" %}

package:
  name: python-geotiepoints
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/python_geotiepoints/python_geotiepoints-{{ version }}.tar.gz
  sha256: d3c022d0d4fd749df9f05d9cb5d25518851a32712c619bfb2fee4812f2674aaf

build:
  number: 0
  skip: true  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - versioneer
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython
    - versioneer
  run:
    - python
    - scipy
    - pandas

test:
  imports:
    - geotiepoints
  requires:
    - h5py

about:
  home: https://github.com/pytroll/python-geotiepoints
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Interpolation of geographic tiepoints in Python
  description: Interpolation and extrapolation of geographic (lon, lat) tie points
  doc_url: http://python-geotiepoints.readthedocs.io
  dev_url: https://github.com/pytroll/python-geotiepoints

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
    - ngam
