{% set version = "1.3.0" %}

package:
  name: python-geotiepoints
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-geotiepoints/python-geotiepoints-{{ version }}.tar.gz
  sha256: 9e539bca00ed7066fd0893f409e047db6345a464db7df497502598261e41b5a8

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]

  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas

test:
  imports:
    - geotiepoints
  requires:
    - h5py

about:
  home: https://github.com/pytroll/python-geotiepoints
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Interpolation of geographic tiepoints in Python
  description: Interpolation and extrapolation of geographic (lon, lat) tie points
  doc_url: http://python-geotiepoints.readthedocs.io
  dev_url: https://github.com/pytroll/python-geotiepoints

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
