{% set version = "1.2.1" %}

package:
  name: python-geotiepoints
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-geotiepoints/python-geotiepoints-{{ version }}.tar.gz
  sha256: e37d3be05af0f268e0a8bddd8536af75a10938ec9d427bfe343e7e88ba1b0168

build:
  number: 2
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - pandas

test:
  imports:
    - geotiepoints
  requires:
    - h5py

about:
  home: https://github.com/pytroll/python-geotiepoints
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Interpolation of geographic tiepoints in Python
  description: Interpolation and extrapolation of geographic (lon, lat) tie points
  doc_url: http://python-geotiepoints.readthedocs.io
  dev_url: https://github.com/pytroll/python-geotiepoints

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
