{% set name = "python-geotiepoints" %}
{% set version = "1.1.7" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "ba29e02402e9284e5e7581b34fe9f31ef12a851be926aa5cde046bb5e56f6041" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script:
    - USE_CYTHON=true  # [not win]
    - set USE_CYTHON=true  # [win]
    - python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython
  run:
    - python
    - numpy
    - scipy
    - pandas

test:
  imports:
    - geotiepoints
  requires:
    - h5py
    - unittest2

about:
  home: https://github.com/pytroll/python-geotiepoints
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Interpolation of geographic tiepoints in Python
  description: Interpolation and extrapolation of geographic (lon, lat) tie points
  doc_url: http://python-geotiepoints.readthedocs.io
  dev_url: https://github.com/pytroll/python-geotiepoints

extra:
  recipe-maintainers:
    - djhoese
    - mraspaud
    - adybbroe
    - pnuu
