travis:
  secure:
    BINSTAR_TOKEN: FGL+wZMLjXap6sopCYZvtEsFJJUHA8C/ifTyH2zrzwr/+yfuYXStxJmIUY6ClOSqXknfkgI3MkBA+5mSrOPf3oYGsQsndG1O8XGfLz6UlZtUHgchv8QrH46qMyZqCYdkbDYqeop1Fb9jHhGn0YRq9Ac/fBC3gTE+F1HKy/T0uAG0nJaPiCNWbPKwMOGOFANRvM9QxSPLMm4bK7OLcZuz/nIv05R4aMXgXFH/Iq4Dj/hf/YlYaoVsgr3Xr9DMa58uT+QC42UtP/stOptv4XLn6f3feYltBpq5O0WAqJJl1BCQhd8Ci7Gt16zxnb0SEuAKBVUV3JYK4fNQoVNOz1/VxoUqSMTKtOrGGarKaKV1M8DmoScq12yXV7L8nm7IQJA6luRtauoR7yrF5rjVjxXCPEPN3WGvTiSj5C+N3vbwt9Txh48AjqnmWOYmG8hCblpuc9F3tqnakJkt6D4n53e/+fcV74BmRyPqvjXZJAdXUag9VlhlpDJdNOvX8MPHNMFuT5/slL8oviFRG5ddvEWulNVyAbsV7WVhZ5qfBoZNIT9Gtm7EbhtS4GpjKlNp1w6KOU5SLDM+l4Si58ArRrNTAqsyuEQ5Plj6uTvzchyCwYDIbhc3m2xAoZke3hW5ARmIrJ7xRUhIzzyPi5oAW5dOgRpvGRBEvDVVP9ZbHznbD90=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
