appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: HojMYpgYAdO3ZO04LXVlvubyI/GyEeGLvFMwM/z2hwt4p17LTPrj3R1gLc91Gha5upQDsSUR+TY9A5jyEddZZiO1ADWo+oylNqTnDXJDjIQtiiDMstl5wfjsAeVdj/VXTv/vB7zFkZZk0kPCRKu1u5PQPavDZQ4nM1RbZ2enkTYPxglBbqULc5k8BWy3OgtvyiKew03R3kOBVD+KlIjAUMHQfQQceLZE+FflnYtaITPT/W203S2MJGmkjpOVp1WPmIpsI605yuRiPZz1IuL5hTD7wkjoJ/91c0B6J4cjBka/My2uevzx7RM3Yr7e7M2LGa663HjVqIg2cLb8zfU76w9DjNiXVSr3y/XFv0qHi8LNU+bAhGPAXT+4HVDLfGV27jk4TRVIloVyTsyfeO4JdeNEkh4RyhOMlhlnVcxrq1ARF9DaVL0xDsyJwHJqnCUgpnfyXEr7DzYs6YAEE7NvjaN1x49Anm6roouEPkCv4zftXoRYv+LnyxZRib/YCO6qaKoPv76AZhOotryKUEI6ZUyief2L5/yYVtjpp5gErslnb1mnHZrydKIQnLtygHvDQvT8zP7OAUbeZiCtGVhgs4xYg92brDr6Z5tIItZR5eMf3bklv6A6wT8VYgFw87ptGxCL6JjR1XgSgWdEFZO6xXVhedsVwEfH0w4sGu6SA6E=}
provider:
  win: azure
conda_forge_output_validation: true
